### ISSUE TITLE
Baking stops on its own on new version 0.3.0 

### ISSUE THREAD

**Issue by felixww1** [bakechain/bakechain#11]
Hi 

This problem has not been solved , it seems the software still stop baking on its own after i update to 0.3.0 version. My OS system is windows 2012 server R2 standard.

**Comment by hclivess** [comment]
Same here. Wimdows 8.1

**Comment by girldrinksgasoline** [comment]
Same on Windows 10

**Comment by NapiaRLT** [comment]
Same problem here. Windows 10 Pro.

**Comment by jupiter50** [comment]
0.3.0 for some reason missed the fix to address this issue. Probably worth upgrading to 0.4.0 which does automatically start baking again (but has other issues as per #16)
