### ISSUE TITLE
Baker Failure

### ISSUE THREAD

**Issue by eduardoalthaus** [bakechain/bakechain#12]
It was all right, with security deposit, delegated balances, and in cycle 8 we received the message 
 **"STATUS BURNT"**. How and why did this happen?
The program has been updated, we are running it 24h, what's the problem?

[View Online](http://tzscan.io/BMLNYZTY2YxiKoTxR41icp7UL87GfFacVZ6q1rU6bj84NUs6Doa)

**Comment by hclivess** [comment]
Interesting, are you sure it didn't stop? I think you have your turn set in advance for a roll, so if the baker was stopped, this could have happened (I have it too)

**Comment by eduardoalthaus** [comment]
> Interesting, are you sure it didn't stop? I think you have your turn set in advance for a roll, so if the baker was stopped, this could have happened (I have it too)

I was monitoring the server and the program, after the update didn't stop anymore.
I'm reading about other people who are having the same problem (burnt blocks).

**Comment by jupiter50** [comment]
Upgrade to 0.4.0 if you haven’t already as there were a lot of changes in there and keep us all on the same page. Burnt block is Stephen’s definition of missing the opportunity to bake. Your part of the network may be fine but then it connects to (Stephen’s) actual full nodes which may have had issues outside of our control. Last night for instance, there were widespread DOS attacks on his and other servers which would have meant more missed baking or endorsement opportunities for a lot of people

**Comment by eduardoalthaus** [comment]
Okay, thanks for the answers. I already mounted a node in Linux, I'll no longer use the GUI. Thank you.
