### ISSUE TITLE
BakeChain  The connection to '45.56.84.80' failed

### ISSUE THREAD

**Issue by TzBaker** [bakechain/bakechain#15]
Hi there,
My app shows pretty much all parameters "0" and when I checked Fiddler I saw the message below. Is it normal behaviour?

![image](https://user-images.githubusercontent.com/41934277/43435547-4fff8374-9435-11e8-913d-3165afb0abd0.png)

[Fiddler] The connection to '45.56.84.80' failed. 
Error: ConnectionRefused (0x274d). 
System.Net.Sockets.SocketException No connection could be made because the target machine actively refused it 45.56.84.80:8338

**Comment by Umadbro33** [comment]
I see this too... after upgrading to .3, the current level and current cycle entries are 0.  This concerns me

**Comment by TzBaker** [comment]
Is it affected baking?

**Comment by Umadbro33** [comment]
I don't know, yet... I only have 1 roll, I have an endorsement scheduled in 16 hr, so I'm curious to see if it misses it while running this version

**Comment by TzBaker** [comment]
Oh...I'll start baking in cycle 12.... please post if yours do not work and maybe I roll back to the previous version 0.2.0

**Comment by Umadbro33** [comment]
will do

**Comment by Umadbro33** [comment]
Looks like newly released version .4 fixed it!  Thanks Stephen!

**Comment by TzBaker** [comment]
We have this problem again :(

**Comment by Umadbro33** [comment]
Yes, it was working fine until I closed bakechain to reboot my computer... when I turned it back on the Current Cycle and Current Level both read 0.  However, I still received endorsements in this condition.  And just this morning, it gave the "low balance" issue again.  Is the network being attacked again?

**Comment by TzBaker** [comment]
Fixed, Thanks!
