### ISSUE TITLE
Version 0.4.0 balance drops to 0, disables baking

### ISSUE THREAD

**Issue by hclivess** [bakechain/bakechain#16]
Hello, with version 0.4.0 balance drops to 0 after some time baking, and disables baking, not making it possible to bake again without restarting the program. Only the main balance is reduced to 0, the rest of the stats on the left side seem correct (including "Actual Balance:")

**Comment by TzBaker** [comment]
Same problem here.

**Comment by bipinsutariyaunh** [comment]
same issue for me also

**Comment by felixww1** [comment]
same issues here

**Comment by Umadbro33** [comment]
yep.

**Comment by sbusher78** [comment]
same issue.  Ive burnt a bake already :(

**Comment by jupiter50** [comment]
I had the same issue too. I suspect this may be down to some of the DOS attacks on the nodes bakechain is connected to. In the 0.4.0 version, you are able to connect to a different node instead of Stephen’s. Unfortunately I don’t know any other nodes to connect to try this out but if others do, may be worth trying to isolate the issue on the server side and/or client side (could also be both)

**Comment by sbusher78** [comment]
Yeah you're probably right. I burnt a bake already which sucks and I feel like I'm losing XTZ by using BakeChain. Dont get me wrong I think Stephen is doing a great job and have donated to him but I just wonder if I'm better off delegating my roll to someone?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jupiter50** [comment]
From my perspective, I don’t want to be paying fees and be totally dependent on delegates; I want to bake myself. Bakechain makes it so much easier so I’m willing to persevere and feed back to Stephen to improve Bakechain. Don’t forget as well, when marketplace opens up, we can earn extra from people delegating to us

**Comment by sbusher78** [comment]
Oh I agree and I will continue using BakeChain. I'm sure he will get it figured out. Have you actually made any XTZ yet? I can't make heads or tails of the awards. Do I lose my bond for the burnt bake?

Where are you from friend? Im in Boston, MA USA

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jupiter50** [comment]
No you don’t lose your bond unless you do something malicious like double bake I believe. 

Yes, have earned some endorsements and due to bake in the next cycle! I’m in Europe :)

**Comment by niiiro** [comment]
I get the message 'Low Balance' after upgrading to v0.4.0

**Comment by jupiter50** [comment]
I also get that message on 0.4.0 intermittently. There are currently issues with the nodes as they are being DOS'd attacked. Sounds like Stephen is looking at this. All bakes and endorsements will be affected. One alternative is to run your own node and point bakechain to it

**Comment by hclivess** [comment]
Thanks, you can try http://api.tzscan.io

**Comment by niiiro** [comment]
So if I want to run my own node - how do I tell the application to use it instead of Sthepen's?

**Comment by jupiter50** [comment]
In v.0.4.0 it is in the settings

**Comment by stephenandrews** [comment]
Fixed in latest version
