### ISSUE TITLE
not endorsing

### ISSUE THREAD

**Issue by jliusyd** [bakechain/bakechain#18]
on bakechain 0.4

failed to endorse twice now

app says i got balance
status:baking

a bug with current deposits
66,475,000,006,956.500ꜩ
and pending rewards 
-66,475,000,006,695.500ꜩ

other stuff comes up as zero, as shown in screen shot
i have tried bakechain's node AND tzscan's node

![untitled](https://user-images.githubusercontent.com/42147866/43724665-de6e3b7a-99dd-11e8-8d00-26a5ca636111.png)

**Comment by Umadbro33** [comment]
Yes, can confirm I am having the same issues.

**Comment by TzBaker** [comment]
Looks like endorsement worked for me, I have the same problem as in the screenshot above.

**Comment by Bake2** [comment]
bakechain_0.6.0
status:BAKING
I have the same problem as in the screenshot above  and missed baking on Cycle16~17

**Comment by stephenandrews** [comment]
Latest version is more stable
