### ISSUE TITLE
Staking power description in Readme is incorrect

### ISSUE THREAD

**Issue by yellowred** [bakechain/bakechain#19]
The Bakechain readme says 
```
Staking Power

Your staking power, which determines how frequent you will be baking and endorsing blocks (similar to hash power in POW chains) is made up of the following:

- Your current balance within your baker
- Any bonds currently being held, for both baking and endorsing (Bake/Endorse Bonds)
- The stake delegated to you (Delegated Stake)
```

Isn't it incorrect, because how frequently you will be baking depends on how many rolls do you have and not simply how many tezzos in your pocket? Source: [Tezos Docs – Running a delegate](http://tezos.gitlab.io/betanet/introduction/howtorun.html#running-a-delegate)

**Comment by stephenandrews** [comment]
Rolls are made up of those 3 elements, rounded down to the nearest 10k XTZ
