### ISSUE TITLE
Baking stops on its own

### ISSUE THREAD

**Issue by gaia** [bakechain/bakechain#2]
Running: Bakechain 0.2.0
OS: Win 10 1803 x64

I leave a dedicated machine running bakechain, no sleep allowed, and from time to time I check in on it to see that "Stop Baking" is back at "Start Baking".

I can't find any logs to look at and I doubt it writes to the event viewer.

How can I get to the bottom of this?

Additionally, is there an API I can use to check to see if my baking status changes so I can get alerted when it stops baking? This is only for mitigation but it would be useful in other scenarios also.

Thank you for your hard work, Stephen!

**Comment by Chadgoe** [comment]
Do you transfer actual Tez into the account to test?

**Comment by stephenandrews** [comment]
I'll look into it for you. There is no API available, but we will be looking at a notification system in future (which would send out an email if the server doesn't hear from you).

**Comment by gaia** [comment]
are there any logs to discover why it stops baking on it's own?

**Comment by stephenandrews** [comment]
Not yet, but will add some in a future release.

**Comment by chrisaut78** [comment]
Hi Stephen, i also have this issue which would be quite a pain when baking starts. can you add a possibility to automaticaly start baker if it stops? Many thanks for your efforts by the way

**Comment by stephenandrews** [comment]
This should be fixed in the latest version (0.3.0)

**Comment by felixww1** [comment]
Hi ,this problem has not been solved , it seems the software still stop baking on its own after i update to 0.3.0 version. My OS system is windows 2012 server R2 standard.

**Comment by girldrinksgasoline** [comment]
This still seems to be happening 0.3.0
