### ISSUE TITLE
2 Burnt Bakes Now

### ISSUE THREAD

**Issue by sbusher78** [bakechain/bakechain#22]
any ideas why I've burnt 2 bakes already? Server and program are up 24/7

**Comment by Bake2** [comment]
I have the same problem on bakechain_0.6.0

**Comment by sbusher78** [comment]
So we are basically losing money.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by stephenandrews** [comment]
Latest version improves baking, but you need to ensure the node you are using is up to date and the time is correct.
