### ISSUE TITLE
Skip blocks

### ISSUE THREAD

**Issue by megapixr** [bakechain/bakechain#24]
Baker always misses the confirmation of the blocks in the Endorsemen, what's the matter?

**Comment by stephenandrews** [comment]
Check your local time to ensure it's correct - if it's even out by a minute you could miss these.

**Comment by megapixr** [comment]
I have a baker installed on a computer that works in Moscow local time

вс, 2 сент. 2018 г. в 12:48, Stephen Andrews <notifications@github.com>:

**Comment by megapixr** [comment]
Hello! Yesterday guys from Norn found problems in the network in connection
with which the network stopped working stably. The baker now does not
confirm the blocks and the reboot does not help. What to do?

**Comment by stephenandrews** [comment]
I you using your own node or the public free one?

**Comment by megapixr** [comment]
I'm using my laptop

вт, 25 сент. 2018 г. в 5:46, Stephen Andrews <notifications@github.com>:

**Comment by stephenandrews** [comment]
What are you using for the backend node though - have you setup your own tezos node? If you are using the public one I suggest you setup your own one and use that for the time being

**Comment by megapixr** [comment]
Maybe I do not quite understand you. I use BakeChain. And after yesterday
the network stopped working, the baker began to have problems

вт, 25 сент. 2018 г. в 5:54, Stephen Andrews <notifications@github.com>:

**Comment by stephenandrews** [comment]
I advise you to setup your own node to use as the backend node until the issues are resolved.
