### ISSUE TITLE
Create new baker - validate date failed

### ISSUE THREAD

**Issue by theLastNail** [bakechain/bakechain#3]
bakechain_app_0.1.0.exe on Windows 10 Home

When trying to create new baker, I'm stuck on the Validate data step. If I enter correct seed and passphrase and hit VALIDATE, the form just reloads with empty fields. (When incorrect data are entered, the incorrect data error message pops up - that's ok).

Thank you for your work!

**Comment by stephenandrews** [comment]
Hi there – please use version 0.1.1 minimum – the 0.1.0 had a bug that did that.

Regards

Sent from Mail for Windows 10

From: theLastNail
Sent: Thursday, July 5, 2018 6:27 PM
To: bakechain/bakechain
Cc: Subscribed
Subject: [bakechain/bakechain] Create new baker - validate date failed (#3)

bakechain_app_0.1.0.exe on Windows 10 Home
When trying to create new baker, I'm stuck on the Validate data step. If I enter correct seed and passphrase and hit VALIDATE, the form just reloads with empty fields. (When incorrect data are entered, the incorrect data error message pops up - that's ok).
Thank you for your work!
