### ISSUE TITLE
Protect https://rpc.tezrpc.me/ from overloading and DDOS attacks

### ISSUE THREAD

**Issue by FlokiTheViking** [bakechain/bakechain#36]
Hi Stephen

As Bakechain uses the same public nodes than Tezbox (https://rpc.tezrpc.me/) and since 7 hours ago are under high load (4-5x above usual high-load levels) as the following statement informs: https://twitter.com/TezBox_Wallet/status/1065203014644916224 , all Bakechainers are missing bakes and endorsements.

The issue is also affecting Tezbox, that cannot even recognise the addresses as part of the blockChain.

It is important for the Bakechain&Tezbox success that you protect your public nodes from over-loading and DDoS attacks. In any case you could reserve some public nodes only for Bakechain, as Tezbox out of service is a problem but Bakechain out of service is critical.

Thanks for your super effort towards the community

**Comment by stephenandrews** [comment]
Public nodes will be attacked regardless, but we will definitely look at a fix. We do run DDoS protection and load balancing, but the high load we are experiencing is appears to be "good traffic", it's just we're at 10x time normal high load levels, and growing (faster than we can deploy additional servers). Hoping to have this sorted soon though!
