### ISSUE TITLE
Block time to long.

### ISSUE THREAD

**Issue by TezTeam** [bakechain/bakechain#39]
Version 3.0.0
The blocks backed with bakechain software are 5 to 6 sec. longer than all the other blocks. And I don't think that's normal. Am I correct?
![block_time](https://user-images.githubusercontent.com/45623951/49505924-0c8d7e00-f87d-11e8-90ff-94205e584f72.png)

**Comment by stephenandrews** [comment]
Hi there - this has no effect on actual baking
