### ISSUE TITLE
Missed 6 blocks on in 2 cycles  

### ISSUE THREAD

**Issue by rubenbur** [bakechain/bakechain#40]
I missed 6 blocks on in 2 cycles but process all 225 endorsements. It kind of strange....   

![image](https://user-images.githubusercontent.com/39499802/49623111-1c8e8600-f981-11e8-8581-f98af55a1862.png)

**Comment by stephenandrews** [comment]
What version are you running? What is your hash rate? Are you using your own node or the public ones?

**Comment by rubenbur** [comment]
What version are you running? 3.0.0
What is your hash rate? 59.711Kh/s
Are you using your own node or the public ones? https://rpc.tezrpc.me

**Comment by stephenandrews** [comment]
Public nodes will likely provide lower bakerates unfortunately as they are shared and can be slow. I am putting together an optimized baking node that will incur a small fee but will be faster for baking and more affordable than runnung your own node.

**Comment by rubenbur** [comment]
That good news. Let me know when I can move to your node.
