### ISSUE TITLE
Missing Bakings

### ISSUE THREAD

**Issue by bradcoolio** [bakechain/bakechain#41]
I have missed two bakings, but I am getting all the Endorsements.  Is there a trouble shooter or any ideas where to start looking for issues?

**Comment by stephenandrews** [comment]
Can you let me know the following:

1) What version are you currently using - go to Settings (the cog icon) where it should be displayed.
2) Run the hardware test from the start screen and let me know the hash rate
3) Are you using your own node, or the free public one

Our recommended guide will generally yield the highest baking efficiency (other than using a ledger, which is purely for security)

**Comment by bradcoolio** [comment]
I ran the hardware test and the hash rate was half what it was originally...that is the problem.  I changed computers.  Thank You.  All is fixed.  Not sure why the Hash rate dropped so much on the same machine.

**Comment by stephenandrews** [comment]
There was a bug that we just fixed. The test was showing higher rates than it should for some devices. You ideally want around 60Kh/s. We are hoping to optimize this more
