### ISSUE TITLE
unlinked and re-linked Ledger and now entire history is gone

### ISSUE THREAD

**Issue by mattnook** [bakechain/bakechain#45]
I recently unplugged my Ledger S from bakechain, then plugged it back in and clicked "Link Ledger" on the landing page of the app. Now I see all my deposits/balance/pending rewards on the left column, but I no longer see any of my pending/paid payouts, endorsements, or bakes. What is happening? I don't want to lose my security deposits because of this app. Please help. My status is on "Baking" but I can't see any of the info that I saw before unplugging.

**Comment by stephenandrews** [comment]
Stats require the tzscan API to display - we find these servers often crash for bakechain users, showing none of the useful stats. The stats aren't required for baking - this uses the core data from the node, so you will continue to bake if that's the case.
