### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by optimum-dulopin** [bakechain/bakechain#46]
Hi,
I recently started to bake, but I'm a bit lost. So i have few questions:

- i 'm currently using bakechain software on a normal laptop, and it seems to be working fine. I previously tried to used it in my rig (6 x RX580 / 8Go), but them I could not use claymore neither xmr-stak to mine xmr or eth at same time). Does bakechain have conflict with these softwareS ? Does it change anything how powerful the computer is ? Are incomes higher with a powerful computer ?

- I started using bakechain yesterday ago. I can see "status: baking", but "capacity: 0%" and on "bakes" tab, it is written : "no bakes available, please start baking" . Am I doing something wrong ?

- it says it is delegated to the same wallet, is that correct ?

- do you have maybe some documentation to help me understand a bit more how this works ;-)

thanks a lot for your help

**Comment by stephenandrews** [comment]
1) Not sure, haven't tested with other software but most likely the issue. For PoS, you don't need amazing specs and a more powerful PC doesn't mean higher income. Make sure you ran the hash test and you got a good enough score.

2) It takes about 3 weeks before you start baking - make sure your delegate is set to yourself, you can monitor via tzscan.io

3) Yup sounds right

4) Only whats in the readme: https://github.com/bakechain/bakechain

**Comment by optimum-dulopin** [comment]
thanks for your answers.
if I have to wait 3 weeks, why is it written "status: baking" ?

also, while waiting this 3 weeks, can I delegate my 10000tz to someone else in order to still be profitable ? if not, does bakechain still need to be on during this 3 weeks ?

**Comment by stephenandrews** [comment]
1) You are baking, but it takes 3 weeks to receive baking rights. You don't need to run the software until you actually have rights to bake.

2) No, you need to keep your tez in your baker for the next 3 weeks - this is the warm up phase. Once you want to finish baking, you can continue doing so 3 weeks after you clear your accounts (as long as you can afford bonds)

**Comment by optimum-dulopin** [comment]
thanks again. much more clear now
just few more questions. 
how will I see that I received baking rights ? will it also be visible on tzscan.io ?
will I also automatically be on mytezosbaker.com and tzscan.io

**Comment by optimum-dulopin** [comment]
hi Stephan 
how are you ? 
I'm contacting you cause I have been baking for a while, everything was ok, but then it stoped to bake and I don't understand why. Endorsing is still going on, but no baking for 55 days, and it displays " 
No block to bake" ( https://tzscan.io/tz1Q41WqokKy1xYiuk5Exkx6DQdDzmgihfwR?default=baking ) . Is there any thing wrong ? 

thanks for your help 



----- Mail original -----

De: "Stephen Andrews" <notifications@github.com> 
À: "bakechain/bakechain" <bakechain@noreply.github.com> 
Cc: "optimum-dulopin" <optimum.dulopin@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 28 Février 2019 15:33:12 
Objet: Re: [bakechain/bakechain] how to (#46) 



    1. 

You are baking, but it takes 3 weeks to receive baking rights. You don't need to run the software until you actually have rights to bake. 
    2. 

No, you need to keep your tez in your baker for the next 3 weeks - this is the warm up phase. Once you want to finish baking, you can continue doing so 3 weeks after you clear your accounts (as long as you can afford bonds)
