### ISSUE TITLE
Sent extra XTZ to BakeChain and How to Update

### ISSUE THREAD

**Issue by sbusher78** [bakechain/bakechain#6]
Hi Stephen,

First of all great job so far you are much appreciated.

I accidentally sent 10,300 or so XTZ to the program and cant figure out how to get the extra out.

Secondly how do I update the program?  I thought I ran the newest installer but I still dont have the Settings button next to the LogOut button.

**Comment by sbusher78** [comment]
disregard the Updating question I figured that out sorry.

**Comment by stephenandrews** [comment]
Hey man,

You need to restore the software on a wallet (like TezBox) to be able to
send it. By design. Bakechain is not a wallet (for added security). You can
export the private key if you need to (in the latest 0.2.0 version)

**Comment by sbusher78** [comment]
Awesome thanks. You wouldn't happen to have directions on restoring it do you? I actually sent them FROM TezBox lol. Also what's your BTC donation address?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by sbusher78** [comment]
So I guess I'm a bit confused. The excess XTZ is in BakeChain. See photo. Are you saying I can restore the BakeChain "wallet" for lack of a better term, into TezBox? Maybe I'm just misunderstanding the whole thing but I'm under the impression that the 10,000 XTZ is a roll I can bake with BakeChain, but the excess 303 wont bake since it's not enough for a second roll. I thought I had to send it back to TezBox and pick a delegate for that 303 XTZ.

I'll send you some XTZ as soon as I can figure this out. Thanks again I know you're probably mad busy.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by sbusher78** [comment]
Wow great ok. I'll let you know when I send yours

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by sbusher78** [comment]
Hate to bother you again but I cant seem to figure this out. I tried to restore the BakeChain account in TezBox using the Seed Words from when I created the BakeChain baker. It restored the wallet fine but the balance is 0. I go to Options and Import but I'm not sure where to find the keys for the Bakechain program. Il probably doing something dumb wrong. I am 100% going to send you some XTZ for your help but I cant do that until I get the extra ~303 out of BakeChain since I sent too much by accident. Cheers!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by sbusher78** [comment]
Disregard my last email I figured it out and all is well. Sent you 10 XTZ for your help and for 2 amazing products. It's not much I know but I wanted to at least give you something. Keep up the great work and cheers from Boston!

Sent from ProtonMail mobile

-------- Original Message --------
