### ISSUE TITLE
How the rewards will be distributed?

### ISSUE THREAD

**Issue by eduardoalthaus** [bakechain/bakechain#7]
Hello Stephen, first of all, congratulations for the program, very useful.
We're running a baker in your app, but some questions have come up if you can help us:

### **1) How will the rewards be distributed?**
For example, someone who invests 500 coins in our baker, how and when will he receive the rewards for leaving those coins there?

Sorry for my ignorance, it's that I come from the system of masternodes and simple wallets, everything at Tezos is very new to me.

### 3) If we send 11000 XTZ to our baker (knowing that the minimum is 10000 XTZ)
will these over 1000 XTZs participate in some form of reward?
Or does this system only work with closed values of 10k?

Thanks.

**Comment by hclivess** [comment]
Hi, you will only get rolls for every 10000 coins.
There is no automatic reward redistribution if someone delegates to you yet, there will be a smart contract later.
8.25% is just an estimation
