### ISSUE TITLE
Noob Questions: Fees and Payment models

### ISSUE THREAD

**Issue by james5652** [bakechain/bakechain#9]
Hi, I would like to start my own baking "node". On mytezosbaker.com are 13 baker nodes and all of them are overdelegated. All of them are using BakeChain? BakeChain is only option how to run baking node today? 

All nodes on mytezosbaker have information about Payment model (dynamic / fixed) and Fee. These values can be set somewhere inside BakeChain? Or how the node owners are paying to participants?

Thank you.

Regards,

James

**Comment by stephenandrews** [comment]
The bakechain software doesn't include payments - this will be included when we add the marketplace extension in the future.
